# -*- coding: utf-8 -*-
"""generate_payroll_cbl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gvRCiRWXcZUlwEPOVd-G_yNZ5q_q3Kv
"""

# generate_payroll_cbl.py
import os

def generate_cobol_file(filename="payroll.cbl", lines=600):
    header = [
        "       IDENTIFICATION DIVISION.",
        "       PROGRAM-ID. PAYROLL.",
        "       AUTHOR. TEST-GENERATOR.",
        "       ENVIRONMENT DIVISION.",
        "       INPUT-OUTPUT SECTION.",
        "       FILE-CONTROL.",
        "           SELECT EMPFILE ASSIGN TO 'EMP.DAT'.",
        "       DATA DIVISION.",
        "       FILE SECTION.",
        "       FD EMPFILE.",
        "       01 EMP-REC.",
        "          05 EMP-ID        PIC 9(5).",
        "          05 EMP-NAME      PIC X(20).",
        "          05 EMP-HOURS     PIC 9(3).",
        "          05 EMP-RATE      PIC 9(3)V99.",
        "       WORKING-STORAGE SECTION.",
        "       01 WS-PAY       PIC 9(5)V99.",
        "       01 WS-TAX       PIC 9(5)V99.",
        "       01 WS-NET       PIC 9(5)V99.",
        "       PROCEDURE DIVISION.",
        "       MAIN-LOGIC.",
        "           PERFORM INIT-ROUTINE.",
        "           PERFORM PROCESS-EMPLOYEES.",
        "           PERFORM END-ROUTINE.",
        "           STOP RUN.",
        "",
    ]

    body = []
    for i in range(lines - len(header) - 10):
        body.append(f"       * Payroll calculation step {i+1}")
        body.append("           COMPUTE WS-PAY = EMP-HOURS * EMP-RATE.")
        body.append("           COMPUTE WS-TAX = WS-PAY * 0.2.")
        body.append("           COMPUTE WS-NET = WS-PAY - WS-TAX.")
        body.append("           DISPLAY 'EMPLOYEE NET PAY: ' WS-NET.")

    footer = [
        "       INIT-ROUTINE.",
        "           DISPLAY 'INITIALIZING PAYROLL SYSTEM'.",
        "           EXIT.",
        "",
        "       PROCESS-EMPLOYEES.",
        "           PERFORM VARYING EMP-ID FROM 1 BY 1 UNTIL EMP-ID > 100",
        "              DISPLAY 'PROCESSING EMPLOYEE ' EMP-ID",
        "           END-PERFORM.",
        "           EXIT.",
        "",
        "       END-ROUTINE.",
        "           DISPLAY 'PAYROLL COMPLETE.'.",
        "           EXIT.",
    ]

    with open(filename, "w") as f:
        f.write("\n".join(header + body + footer))

    print(f"Generated {filename} with {lines} lines.")

if __name__ == "__main__":
    generate_cobol_file()