# -*- coding: utf-8 -*-
"""code_search_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gvRCiRWXcZUlwEPOVd-G_yNZ5q_q3Kv
"""

# tools/code_search_tool.py
import chromadb
import os
from openai import AzureOpenAI
from config import (
    # Embedding model configs (needed to embed the query)
    AZURE_OPENAI_KEY_EMB,
    AZURE_OPENAI_ENDPOINT_EMB,
    AZURE_OPENAI_API_VERSION_EMB,
    AZURE_OPENAI_EMB_MODEL, # Your embedding deployment name
    # ChromaDB config
    CHROMA_COLLECTION
)
# ==============================
# Setup Azure OpenAI Embedding Client
# ==============================


llm_embedding_client = AzureOpenAI(
    api_key=AZURE_OPENAI_KEY_EMB,
    api_version=AZURE_OPENAI_API_VERSION_EMB,
    azure_endpoint=AZURE_OPENAI_ENDPOINT_EMB,
)


def embed_text(text: str):
    """Generate embedding for a single text string using Azure OpenAI."""
    response = llm_embedding_client.embeddings.create(
        model=AZURE_OPENAI_EMB_MODEL,
        input=text
    )
    return response.data[0].embedding


# ==============================
# Setup Chroma DB
# ==============================
DB_PATH = r"./chroma_db"
os.makedirs(DB_PATH, exist_ok=True)

chroma_client = chromadb.PersistentClient(path=DB_PATH)
collection = chroma_client.get_or_create_collection(CHROMA_COLLECTION)


# ==============================
# Search Tool
# ==============================
def code_search_tool(query: str) -> str:
    print(f"[code_search_tool] Searching for: {query}")

    # Get query embedding
    query_embedding = embed_text(query)

    # Perform similarity search
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=3
    )

    docs = results.get("documents", [[]])[0]
    context = "\n".join(docs)

    return context if context else "No relevant code found."