# -*- coding: utf-8 -*-
"""debug_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gvRCiRWXcZUlwEPOVd-G_yNZ5q_q3Kv
"""

from langchain_openai import AzureChatOpenAI
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
import os

load_dotenv()

llm_chat_client = AzureChatOpenAI(azure_deployment=os.getenv("OPENAI_DEPLOYMENT_NAME_8K"),
                      api_version=os.getenv("OPENAI_API_VERSION"),
                      api_key=os.getenv("OPENAI_API_KEY"),
                      azure_endpoint=os.getenv("AZURE_ENDPOINT"),
                      temperature= 0,
                      max_tokens=8000,
                      #top_p=0.1
                 )

def debug_tool(error_message: str, faulty_code: str) -> str:
    print(f"---------- Faulty code-------------\n {faulty_code}")
    prompt = f"""
        Error:
        {error_message}

        Faulty Code:
        {faulty_code}

        Return only the corrected Python code.
        Do not include explanations, comments, or extra text.
        """
    messages = [
        SystemMessage(content="""You are an expert Python developer and debugging assistant.Your\
             only task is to output corrected Python code based on the given error
                and faulty code. Respond with valid Python code only — no explanations,
                no comments, no markdown formatting."""),
        HumanMessage(content=prompt)
    ]

    print(f"{error_message}: Debugging...")
    response = llm_chat_client.invoke(messages)
    print(f"---------------------------------------------Debugged code---------------\n {response.content.strip()}")
    return response.content.strip()