# -*- coding: utf-8 -*-
"""linter_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gvRCiRWXcZUlwEPOVd-G_yNZ5q_q3Kv
"""

# tools/linter_tool.py
import subprocess
import tempfile
import os
import sys

def linter_tool(code: str) -> (bool, str):
    """
    Run pylint on the code string by writing to a temp file.
    Returns (passed: bool, error_message: str)
    """
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False, mode="w") as tmp:
        tmp.write(code)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            [sys.executable, "-m", "pylint", tmp_path, "--disable=all", "--enable=syntax-error"],
            capture_output=True,
            text=True,
            timeout=10
        )
        passed = (result.returncode == 0)
        error_msg = result.stdout if not passed else ""
    except FileNotFoundError:
        passed = False
        error_msg = "pylint is not installed. Please install it with: pip install pylint"
    except Exception as e:
        passed = False
        error_msg = str(e)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    return passed, error_msg